### ISSUE TITLE
Disabled button during loading is blue

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4167]
ER:
Button spinner is transparent + white

AR:
Button spinner is transparent + grey

![grey](https://cloud.githubusercontent.com/assets/68213/18637131/5e54ed9a-7e59-11e6-88b4-76feea46517a.gif)

**Comment by TDA** [comment]
I might be completely wrong, but isn't this by design? @ryanfeeley 

```
.button-row & {
    @include hidpi-background-image('spinnergrey', 33px 33px);
```

**Comment by ryanfeeley** [comment]
@TDA Ah, so perhaps the problem is that the button should not be blue during this state. So the spinner is right, the button is wrong?

**Comment by TDA** [comment]
@ryanfeeley I am afraid that might be the case, is this behavior noticed elsewhere?

**Comment by ryanfeeley** [comment]
@TDA I haven't noticed it yet…

**Comment by 13nehu** [comment]
I am interested to solve this issue. can you please tell me what exactly is required to be done?

**Comment by TDA** [comment]
@13nehu You would need to do the following:
1. Ensure that the button color changes to white color instead of staying blue.
2. Test that the changes are not affecting our other buttons.
3. Do a sanity check so that none of our other buttons are having this issue.
Goodluck! 👍

**Comment by vladikoff** [comment]
@13nehu to reproduce issue locally try this:

* Setup the fxa-content-server locally: https://github.com/mozilla/fxa-content-server#quick-start
* Clone this branch of the 123done repository: https://github.com/mozilla/123done/tree/content_oauth, run `npm install` and `npm start`.
* Clone this project: https://github.com/vladikoff/fxa-dev-launcher, run `npm install` and start it with `FXA_ENV=content npm start`
* That last command should start the Firefox browser with special configuration. Sign in to Sync (Create a Firefox account with that browser)
* Now in the same browser open https://123done-content.dev.lcip.org/  and try to Sign In with the same account: 

![image](https://cloud.githubusercontent.com/assets/128755/18848380/16e93846-83fc-11e6-89eb-6ec2fb4f46ae.png)

You will notice that the button has a grey spinner.  See this note to work on CSS for this: https://github.com/mozilla/fxa-content-server#changes-to-stylesheets
Let me know if you have questions.

**Comment by pearl98** [comment]
I am having problem during setup,How can I contact you in IRC?

**Comment by vladikoff** [comment]
> I am having problem during setup,How can I contact you in IRC?

Join the Mozilla IRC, join the `#fxa` channel and mention `vladikoff` in that channel so we can help you :)

**Comment by Anisha1234** [comment]
I tried to reprodcue the bug and found that , it is already solved.So please remove this from backlog
:-)

**Comment by vladikoff** [comment]
this is still a problem as of b8952f0c4164f26016356ff6caf7286e509b8c55

**Comment by ryanfeeley** [comment]
![grey-button](https://cloud.githubusercontent.com/assets/68213/19451481/6417352a-947b-11e6-93fd-0b94b9bed7e9.gif)

**Comment by ryanfeeley** [comment]
still an issue
<img width="685" alt="screenshot 2016-12-20 19 50 54" src="https://cloud.githubusercontent.com/assets/68213/21373518/b302cc68-c6ed-11e6-85ed-88fd76f4ddee.png">
