### ISSUE TITLE
Fix checksum-ed naming of css files

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#4189]
Ref: #4187 

`
But this points out that the checksum of all the css files is not a checksum (correct md5 or not) of the final css file content, but a checksum of presumably some earlier form of the css content.
`

In #4187, the `.css` deadbeef names did not change, yet actual content was different.

**Comment by shane-tomlinson** [comment]
Can you explain further what is happening?

**Comment by vladikoff** [comment]
```
[15:56:15]  <jbuck>	str: nvm use 0.10 && npm install && grunt build && mv dist old-dist && nvm use 4 && npm rebuild && grunt build && mv dist new-dist. then just diff the two directories

[16:12:45]  <jbuck>	vladikoff: and to test whether something is working correctly... look at 500.html in the dist directory
[16:12:58]  <jbuck>	if it's broken it'll have the same filename with a different integrity hash for each directory
```

**Comment by vladikoff** [comment]
I think this was fixed, @jbuck let me know if there are other problems

**Comment by jrgm** [comment]
This is not fixed. Run this script:
```
#!/usr/bin/env sh

set -e

. ~/.nvm/nvm.sh

# Do a clean pull of content-server
cd /tmp/fxa-content-server
nvm use 0.10

for tag in v0.69.0 v0.70.0 v0.70.1; do 
  echo @@ $tag @@
  git clean -fdx
  git checkout $tag
  npm install
  grunt build
  /bin/rm -rf /tmp/dist-${tag}
  mkdir -p /tmp/dist-${tag}
  /bin/mv ./dist /tmp/dist-${tag}
done
```
And then use https://gist.github.com/jrgm/c3ff3ebf1bb0fc02febe273a118af087 like so:
`node deltas.js /tmp/dist-v{0.69.0,0.70.0}/dist`
`node deltas.js /tmp/dist-v{0.70.0,0.70.1}/dist`
Basically, if the checksum-ed name of a font file changes **either incorrectly (interpreting it as utf8 as seen in node4), or correctly (updated with fixed grunt-file-rev** the `css` files' checksummed names are not recomputed, and the SRI checks are also wrong.

**Comment by jrgm** [comment]
Following on from above, if I upload the `./dist` content into `s3` for `cloudfront`, **all CSS will fail to load**.

**Comment by shane-tomlinson** [comment]
I'm looking through the list of files now. One thing I find strange is the `fonts` CSS subdirectory is copied to prod, it doesn't need to be, no prod templates include any CSS from that directory:

```bash
➜  dist git:(master) pwd                                             git:(master|)
/Users/stomlinson/development/fxa-content-server/server/templates/pages/dist
➜  dist git:(master) rgrep -i "fonts" .                              git:(master|)
➜  dist git:(master)
```
