### ISSUE TITLE
accounts.firefox.com login does not autocomplete in Chrome

### ISSUE THREAD

**Issue by bfred-it** [mozilla/fxa-content-server#4774]
### Describe the problem and steps to reproduce it:

[accounts.firefox.com/signin](https://accounts.firefox.com/signin) does not autofill any information on Chrome. No email, no password.

1. Open Google Chrome
2. Visit https://accounts.firefox.com/signin
3. Start typing your email address

### What happened?

Issue 1: the email does not autocomplete
Issue 2: the password does not autocomplete, even if Chrome will recognize the login and save it successfully

### What did you expect to happen?

Email and password autocomplete like they do in Firefox

**Comment by vladikoff** [comment]
This should be fixed:

![image](https://user-images.githubusercontent.com/128755/29378559-7f5427d4-828d-11e7-8af2-8085ccdb07a2.png)

**Comment by bfred-it** [comment]
Excellent! Now only a minor visual issue remains: Sign in button stays gray (it normally turns blue when you enter the pass) but it still works:

![mmm](https://user-images.githubusercontent.com/1402241/29650252-f6002e28-88c3-11e7-8b5e-0cbbb5673d3e.gif)

(in this gif it turns blue after I click somewhere else)
