### ISSUE TITLE
Refreshing device manager after several hours is invalid

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4949]
STEPS TO REPRODUCE
1. Log in to device manager
2. Leave tab open
3. Go to work
4. Perhaps visit device manager there
5. Return home to still-open device manager tab and press Refresh

EXPECTED RESULTS
* Devices refresh

ACTUAL RESULTS
* Invalid assertion error
<img width="635" alt="screenshot 2017-04-12 20 23 55" src="https://cloud.githubusercontent.com/assets/68213/24984846/2a7d0fc8-1fbe-11e7-8637-bcbc894bc781.png">

**Comment by vladikoff** [comment]
Ah interesting, I thought we fixed this. Good find!

**Comment by shane-tomlinson** [comment]
Down with assertions!

**Comment by ryanfeeley** [comment]
I still get this error. <img width="626" alt="screenshot 2017-06-18 18 27 20" src="https://user-images.githubusercontent.com/68213/27297932-c52d0f12-54f4-11e7-93c4-b5ea4eb7c225.png">

**Comment by ryanfeeley** [comment]
What if the full page reloaded instead of throwing this error?

**Comment by ryanfeeley** [comment]
If the page needs to be reloaded, can we do that for the user instead of throwing this error?

**Comment by rfk** [comment]
I don't think a reload should be necessary - instead, we need to keep track of the timestamp at which we generated our assertion, and generate a fresh one if it's more than X minutes old.

**Comment by vladikoff** [comment]
@rfk We already have an error handler here: https://github.com/mozilla/fxa-content-server/blob/39bb7715c00150b9037ce07fcc829ba4824ae376/app/scripts/models/account.js#L891 

Do you think we are missing the "Invalid Assertion" check there? Also as it says here these last for 25 years: https://github.com/mozilla/fxa-content-server/blob/39bb7715c00150b9037ce07fcc829ba4824ae376/app/scripts/models/account.js#L199 

So i'm not sure what is going on, I switched the TTL to 10 seconds and it correctly handles the error case.

**Comment by rfk** [comment]
> Also as it says here these last for 25 years

After digging into it a bit, it turns out that comment is mistaken :-)

Assertions have two expiry times.  There's the expiry time put on it locally by the client, which the content-server does indeed set to 25 years.  There's also the expiry time on the underlying signed certificate, which the auth-server will cap at 24 hours max:

  https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/sign.js#L40

But which the content-server only requests be valid for 6 hours:

  https://github.com/mozilla/fxa-content-server/blob/39bb7715c00150b9037ce07fcc829ba4824ae376/app/scripts/lib/assertion.js#L12

It's probably that 6-hour window that's expiring and causing this bug.

**Comment by rfk** [comment]
So basically the code at [1] is built on a faulty assumption - it thinks that assertions will last for a very long time and can be cached indefinitely, but that will only be valid for 6 hours max.  It needs to grow the ability to throw away expired assertions and generate a fresh one.

[1] https://github.com/mozilla/fxa-content-server/blob/39bb7715c00150b9037ce07fcc829ba4824ae376/app/scripts/models/account.js#L193

**Comment by rfk** [comment]
I'm able to trigger this bug reliably  by reducing the oauth token ttl and identity cert duration to 10 seconds, so I'm pretty confident that the above explanation is what's going on.  I'm going to try adding a little refresh logic and see if that fixes it.

**Comment by rfk** [comment]
@shane-tomlinson question: why do we need to cache the assertions at all?  IIUC the only reason this code uses an assertion is to generate an OAuth token, and it already caches the OAuth tokens and correctly refreshes them if they expire.  Could we fix this bug by just removing the caching of assertions?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson question: why do we need to cache the assertions at all? IIUC the only reason this code uses an assertion is to generate an OAuth token, and it already caches the OAuth tokens and correctly refreshes them if they expire. Could we fix this bug by just removing the caching of assertions?

I am in total ignorance/bliss of this portion of the system. I think the idea was when the OAuth tokens expire, we could refresh them using the cached assertion.

**Comment by ryanfeeley** [comment]
I'm still seeing this. In the meantime, can we say something more intelligible to users? Like: "Cannot load list. Refresh the page."

**Comment by rfk** [comment]
Hrmph, I was expecting this to be fixed in train-95; @ryanfeeley using same STR as before?

**Comment by vladikoff** [comment]
@shane-tomlinson to double check...

**Comment by shane-tomlinson** [comment]
@ryanfeeley is right... :(

<img width="641" alt="screen shot 2017-09-19 at 10 01 36" src="https://user-images.githubusercontent.com/848085/30584544-9ea3a942-9d19-11e7-8ba5-06eb3eab1587.png">

<img width="1206" alt="screen shot 2017-09-19 at 10 05 26" src="https://user-images.githubusercontent.com/848085/30584593-c55ea258-9d19-11e7-9bdb-2c0acd20c16d.png">

**Comment by rfk** [comment]
Any chance you can capture the assertion from request body in the network view for further debugging?

**Comment by shane-tomlinson** [comment]
> Any chance you can capture the assertion from request body in the network view for further debugging?

I restarted to get the new nightly, now have to wait 6 hours.

**Comment by shane-tomlinson** [comment]
I found the problem... More details coming shortly.

**Comment by shane-tomlinson** [comment]
The problem is... When we create expiredAt to compare against createdAt, we always set expiredAt to *1 hour from now*. 

See https://github.com/mozilla/fxa-content-server/blob/ead2f2cbb5fb061f713f514dd44302ae78505788/app/scripts/models/account.js#L216:L217

```js
const expiredAt = new Date();
expiredAt.setHours(expiredAt.getHours() + 1);
```
