### ISSUE TITLE
Some SVG device icons will not load

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5073]
I noticed that the Android tablet icon would not load.
<img width="550" alt="screen shot 2017-05-17 at 11 31 21 am" src="https://cloud.githubusercontent.com/assets/68213/26162323/6ab0d2e0-3af4-11e7-9772-519886a51209.png">

I inspected it and saw this:
<img width="366" alt="screen shot 2017-05-17 at 11 31 17 am" src="https://cloud.githubusercontent.com/assets/68213/26162324/6ae79fe6-3af4-11e7-8732-38a2c2048125.png">

Oddly when I downloaded the file, it would open fine. Ideas?

**Comment by shane-tomlinson** [comment]
It's possible that file has an inline `style` element, if that's the case, we'll have to add it's sha to our CSP rules.

**Comment by shane-tomlinson** [comment]
> It's possible that file has an inline style element, if that's the case, we'll have to add it's sha to our CSP rules.

That file contains:

> <style>path,rect{fill:#505050}#screen{fill-opacity:.1}#icon{fill-opacity:.6}</style>

When you open the dev console, do you see any security errors?

**Comment by shane-tomlinson** [comment]
Hmm.. The phone icon has the same style element, yet works just fine.

**Comment by shane-tomlinson** [comment]
Even more hmmm... I have no problems viewing the Android icon on a tablet.

**Comment by ryanfeeley** [comment]
it's not limited to the android tablet. spotted this too. <img width="248" alt="screen shot 2017-05-16 at 3 07 43 pm" src="https://cloud.githubusercontent.com/assets/68213/26169733/c2a4bf30-3b0c-11e7-9779-bb010e08d3db.png">

**Comment by shane-tomlinson** [comment]
How can we get Softvision involved in trying to reproduce this?

**Comment by vladikoff** [comment]
This seems like a CDN bug:

https://accounts.cdn.mozilla.net/images/5f50bfb8.icon-device-laptop-mac.svg

vs

https://accounts.firefox.com/images/5f50bfb8.icon-device-laptop-mac.svg


The CDN resource asks me to download the thing:

![image](https://cloud.githubusercontent.com/assets/128755/26285214/63323824-3e19-11e7-994d-b88c6103fc1c.png)


The CDN `laptop-mac` is served as `binary/octet-stream`:

![image](https://cloud.githubusercontent.com/assets/128755/26285222/91ed04b4-3e19-11e7-85e2-15ed9ce54f67.png)

Other icons are proper `svg`

**Comment by vladikoff** [comment]
cc @jrgm @jbuck ^

**Comment by jbuck** [comment]
@jrgm Re-uploaded all content on May 22nd 5:31PM EST.

As to why this happened... I have no idea.

**Comment by vladikoff** [comment]
This was fixed

**Comment by davismtl** [comment]
Should this be visible in release now or is it coming out on an upcoming train?

**Comment by rfk** [comment]
My impression is it should be fixed in release, since the fix was a push to the CDN.

**Comment by davismtl** [comment]
> My impression is it should be fixed in release, since the fix was a push to the CDN.

Based on IRC conversation, this still doesn't seem to be working. Re-open or file new issue?

For example, I don't see the icons:
![screen shot 2017-05-24 at 1 52 37 pm](https://cloud.githubusercontent.com/assets/19537086/26425871/3d0c65e2-408b-11e7-89fe-4c502106ef2b.png)
